bioinfoweb/helpdesk/urls.py
"""
django-helpdesk - A Django powered ticket tracker for small enterprise.

(c) Copyright 2008 Jutda. All Rights Reserved. See LICENSE for details.

urls.py - Mapping of URL's to our various views. Note we always used NAMED
          views for simplicity in linking later on.
"""

from django.conf import settings
import django
if django.get_version().startswith("1.3"):
	from django.conf.urls.defaults import *
else:
	from django.conf.urls import *
from django.contrib.auth.decorators import login_required

from helpdesk import settings as helpdesk_settings
from helpdesk.views import feeds, staff, public, api, kb
from django.contrib.auth import views as auth_views

from django.views.generic import TemplateView
class DirectTemplateView(TemplateView):
    extra_context = None
    def get_context_data(self, **kwargs):
        context = super(self.__class__, self).get_context_data(**kwargs)
        if self.extra_context is not None:
            for key, value in self.extra_context.items():
                if callable(value):
                    context[key] = value()
                else:
                    context[key] = value
        return context

urlpatterns = [
    url(r'^dashboard/$',
        staff.dashboard,
        name='helpdesk_dashboard'),

    url(r'^tickets/$',
        staff.ticket_list,
        name='helpdesk_list'),

    url(r'^tickets/update/$',
        staff.mass_update,
        name='helpdesk_mass_update'),

    url(r'^tickets/submit/$',
        staff.create_ticket,
        name='helpdesk_submit'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/$',
        staff.view_ticket,
        name='helpdesk_view'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/followup_edit/(?P<followup_id>[0-9]+)/$',
        staff.followup_edit,
        name='helpdesk_followup_edit'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/followup_delete/(?P<followup_id>[0-9]+)/$',
        staff.followup_delete,
        name='helpdesk_followup_delete'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/edit/$',
        staff.edit_ticket,
        name='helpdesk_edit'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/update/$',
        staff.update_ticket,
        name='helpdesk_update'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/delete/$',
        staff.delete_ticket,
        name='helpdesk_delete'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/hold/$',
        staff.hold_ticket,
        name='helpdesk_hold'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/unhold/$',
        staff.unhold_ticket,
        name='helpdesk_unhold'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/cc/$',
        staff.ticket_cc,
        name='helpdesk_ticket_cc'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/cc/add/$',
        staff.ticket_cc_add,
        name='helpdesk_ticket_cc_add'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/cc/delete/(?P<cc_id>[0-9]+)/$',
        staff.ticket_cc_del,
        name='helpdesk_ticket_cc_del'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/dependency/add/$',
        staff.ticket_dependency_add,
        name='helpdesk_ticket_dependency_add'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/dependency/delete/(?P<dependency_id>[0-9]+)/$',
        staff.ticket_dependency_del,
        name='helpdesk_ticket_dependency_del'),

    url(r'^tickets/(?P<ticket_id>[0-9]+)/attachment_delete/(?P<attachment_id>[0-9]+)/$',
        staff.attachment_del,
        name='helpdesk_attachment_del'),

    url(r'^raw/(?P<type>\w+)/$',
        staff.raw_details,
        name='helpdesk_raw'),

    url(r'^rss/$',
        staff.rss_list,
        name='helpdesk_rss_index'),

    url(r'^reports/$',
        staff.report_index,
        name='helpdesk_report_index'),

    url(r'^reports/(?P<report>\w+)/$',
        staff.run_report,
        name='helpdesk_run_report'),

    url(r'^save_query/$',
        staff.save_query,
        name='helpdesk_savequery'),

    url(r'^delete_query/(?P<id>[0-9]+)/$',
        staff.delete_saved_query,
        name='helpdesk_delete_query'),

    url(r'^settings/$',
        staff.user_settings,
        name='helpdesk_user_settings'),

    url(r'^ignore/$',
        staff.email_ignore,
        name='helpdesk_email_ignore'),

    url(r'^ignore/add/$',
        staff.email_ignore_add,
        name='helpdesk_email_ignore_add'),

    url(r'^ignore/delete/(?P<id>[0-9]+)/$',
        staff.email_ignore_del,
        name='helpdesk_email_ignore_del'),
]

urlpatterns += [
    url(r'^$',
        public.homepage,
        name='helpdesk_home'),

    url(r'^view/$',
        public.view_ticket,
        name='helpdesk_public_view'),

    url(r'^change_language/$',
        public.change_language,
        name='helpdesk_public_change_language'),
]

urlpatterns += [
    url(r'^rss/user/(?P<user_name>[^/]+)/$',
        login_required(feeds.OpenTicketsByUser()),
        name='helpdesk_rss_user'),

    url(r'^rss/user/(?P<user_name>[^/]+)/(?P<queue_slug>[A-Za-z0-9_-]+)/$',
        login_required(feeds.OpenTicketsByUser()),
        name='helpdesk_rss_user_queue'),

    url(r'^rss/queue/(?P<queue_slug>[A-Za-z0-9_-]+)/$',
        login_required(feeds.OpenTicketsByQueue()),
        name='helpdesk_rss_queue'),

    url(r'^rss/unassigned/$',
        login_required(feeds.UnassignedTickets()),
        name='helpdesk_rss_unassigned'),

    url(r'^rss/recent_activity/$',
        login_required(feeds.RecentFollowUps()),
        name='helpdesk_rss_activity'),
]


urlpatterns += [
    url(r'^api/(?P<method>[a-z_-]+)/$',
        api.api,
        name='helpdesk_api'),

    url(r'^login/$',
        auth_views.login,
        {'template_name': 'helpdesk/registration/login.html'},
        name='login'),

    url(r'^logout/$',
        auth_views.logout,
        {'template_name': 'helpdesk/registration/login.html', 'next_page': '../'},
        name='logout'),
]

if helpdesk_settings.HELPDESK_KB_ENABLED:
    urlpatterns += [
        url(r'^kb/$',
            kb.index,
            name='helpdesk_kb_index'),

        url(r'^kb/(?P<item>[0-9]+)/$',
            kb.item,
            name='helpdesk_kb_item'),

        url(r'^kb/(?P<item>[0-9]+)/vote/$',
            kb.vote,
            name='helpdesk_kb_vote'),

        url(r'^kb/(?P<slug>[A-Za-z0-9_-]+)/$',
            kb.category,
            name='helpdesk_kb_category'),
    ]

urlpatterns += [
    url(r'^api/$',
        TemplateView.as_view(template_name='helpdesk/help_api.html'),
        name='helpdesk_api_help'),

    url(r'^help/context/$',
        TemplateView.as_view(template_name='helpdesk/help_context.html'),
        name='helpdesk_help_context'),

    url(r'^system_settings/$',
        DirectTemplateView.as_view(template_name='helpdesk/system_settings.html'),
        name='helpdesk_system_settings'),
]

bioinfoweb/pqanalysis/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.add_attachment, name='add_attachment'),
  url(r'^results/$', views.view_results, name='view_results'),
  url(r'^upload/$', views.worklist_upload, name='upload-new'),
  url(r'^delete-worklist/(?P<pk>\d+)$', views.worklist_delete, name='upload-delete'),
  url(r'^worklist/$', views.get_worklist_update, name='update-worklist'),
  url(r'^prepopulate-worklist/(?P<pk>\d+)$', views.worklist_get, name='pp-worklist'),
  url(r'^prepopulate-limitslist/(?P<pk>\d+)$', views.limitslist_get, name='pp-limitslist'),
  url(r'^prepopulate-worklist-tma/(?P<pk>\d+)$', views.worklist_get_tma, name='pptma-worklist'),
  url(r'^prepopulate-limitslist-tma/(?P<pk>\d+)$', views.limitslist_get_tma, name='pptma-limitslist'),
  url(r'^prepopulate-recovery-tma/(?P<pk>\d+)$', views.recovery_get_tma, name='pptma-recovery'),
  url(r'^worklist-upload/(?P<type_of>\w+)/$', views.ajax_uploaded_worklist, name='ajax-upload-worklist'),
  url(r'^limits-upload/(?P<type_of>\w+)/$', views.ajax_uploaded_limits, name='ajax-upload-limits'),
  url(r'^recovery-upload/$', views.ajax_uploaded_recovery, name='ajax-upload-recovery'),
  url(r'^limitslist/$', views.get_limitslist_update, name='update-limitslist'),
  url(r'^recoverylist/$', views.get_recovery_update, name='update-recoverylist')
]

bioinfoweb/tech/urls.py
from django.conf.urls import patterns, url
from tech import views

urlpatterns = [	url(r'^$', views.index, name='tech_home'),
		url(r'^tma/$', views.tech_tma, name='tech_tma'),
		url(r'^invader/$', views.tech_invader, name='tech_invader'),
]

bioinfoweb/pqanalysis/models.py
from django.db import models
import os


def upload_to(instance, filename):
  """ Custom upload modifier method that will help
  create a unique directory to store a group of files.
  The unique directory is generated by a name given
  by the user as well as a timestamp appended to the name.

  Args:
    instance - the file instance from post request (file obj)
    filename - the actual string representation of filename (str)
  Returns:
    the location to save the file (str)
  """

  # base_media_dir = "files/media/pqanalysis/"
  save_directory = instance.analysis_id
  filename_base, filename_ext = os.path.splitext(filename)

  # new_implentation
  return "pqresults/" + save_directory + "/" + instance.analysis_id + "_" + filename_base + filename_ext.lower()


# old_implementation - before name change
# return "pqresults/" + save_directory + "/" + filename_base + filename_ext.lower()

class PqAttachment(models.Model):
  analysis_id = models.CharField(max_length=100)
  file_name = models.CharField(max_length=100)
  attachment = models.FileField(upload_to=upload_to, max_length=1000)
  submitter = models.CharField(max_length=100)
  date_submitted = models.DateField(auto_now_add=True)


class PqResults(models.Model):
  pqresults = models.ForeignKey(PqAttachment, on_delete=models.CASCADE)
  pq_file_name = models.CharField(max_length=100)
  file_dir = models.FileField(upload_to=None, max_length=1000)


class CombineResults(models.Model):
  combine_file_name = models.CharField(max_length=100)
  combine_file_dir = models.FileField(upload_to="pqcombined", max_length=1000)
  date_uploaded = models.DateField(auto_now_add=True)


class RecoveryRate(models.Model):
  class Meta:
    verbose_name = "recovery"
    verbose_name_plural = "recovery"

  filename = models.CharField(max_length=1000)
  file = models.FileField(upload_to="recovery")
  slug = models.SlugField(max_length=1000, blank=True)
  upload_date = models.DateField(auto_now_add=True)
  recovery_type = models.CharField(max_length=1000)

  def __str__(self):
    return self.filename

  def __unicode__(self):
    return self.filename


class Worklist(models.Model):

  class Meta:
    verbose_name = "worklist"
    verbose_name_plural = "worklists"


  """ Storing user worklist """
  filename = models.CharField(max_length=1000)
  file = models.FileField(upload_to="worklist")
  slug = models.SlugField(max_length=1000, blank=True)
  upload_date = models.DateField(auto_now_add=True)
  worklist_type = models.CharField(max_length=1000)


  def __str__(self):
    return self.filename


  def __unicode__(self):
    return self.filename


  def get_absolute_url(self):
    return ('upload-delete',)


  def save(self, *args, **kwargs):
    self.slug = self.file.name
    super(Worklist, self).save(*args, **kwargs)


  def delete(self, *args, **kwargs):
    self.file.delete(False)
    super(Worklist, self).delete(*args, **kwargs)


class RunRecovery(models.Model):
  """
  Recovery Rates
  """
  class Meta:
    verbose_name = 'recovery'
    verbose_name_plural = 'recovery'

  filename = models.CharField(max_length=1000)
  file = models.FileField(upload_to="recovery")
  slug = models.SlugField(max_length=1000, blank=True)
  upload_date = models.DateField(auto_now_add=True)

  def __str__(self):
    return self.filename

  def __unicode__(self):
    return self.filename


class Limits(models.Model):
    """ Storing user worklist """

    class Meta:
        verbose_name = 'limit'
        verbose_name_plural = 'limits'

    filename = models.CharField(max_length=1000)
    file = models.FileField(upload_to="limits")
    slug = models.SlugField(max_length=1000, blank=True)
    upload_date = models.DateField(auto_now_add=True)
    limits_type = models.CharField(max_length=1000)

    def __str__(self):
        return self.filename

    def __unicode__(self):
        return self.filename

    def get_absolute_url(self):
        return ('upload-delete',)

    def save(self, *args, **kwargs):
        self.slug = self.file.name
        super(Limits, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.file.delete(False)
        super(Limits, self).delete(*args, **kwargs)

bioinfoweb/pqanalysis/forms.py
from django import forms
from .models import Worklist, Limits, RunRecovery


class RunRecoveryForm(forms.Form):
  class Meta:
    model = RunRecovery
    fields = ['file']

  file_upload_selection_recovery = forms.ModelChoiceField(
    queryset=RunRecovery.objects.all(),
    initial=1,
    widget=forms.Select(attrs={'class':'form-control'})
  )


class WorklistInputForm(forms.Form):
  class Meta:
    model = Worklist
    fields = ['file']

  file_upload_selection = forms.ModelChoiceField(
    queryset=Worklist.objects.filter(worklist_type__iexact='fusion'),
    initial=1,
    widget=forms.Select(attrs={'class': 'form-control'})
  )

  file_upload_selection_tma = forms.ModelChoiceField(
    queryset=Worklist.objects.filter(worklist_type__iexact='tma'),
    initial=1,
    widget=forms.Select(attrs={'class': 'form-control'})
  )


class LimitsInputForm(forms.Form):
  class Meta:
    model = Limits
    fields = ['file']

  file_limits_upload_selection = forms.ModelChoiceField(
    queryset=Limits.objects.filter(limits_type__iexact='fusion'),
    initial=1,
    widget=forms.Select(attrs={'class': 'form-control'})
  )

  file_limits_upload_selection_tma = forms.ModelChoiceField(
    queryset=Limits.objects.filter(limits_type__iexact='tma'),
    initial=1,
    widget=forms.Select(attrs={'class': 'form-control'})
  )

bioinfoweb/pqanalysis/templates/pqanalysis/base_pqanalysis.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/pqanalysis.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery.fileupload-ui.css' %}">
{% endblock %}
{% block content %}
{% endblock %}
{% block js %}
<!-- Placed at the end of the document for faster load times -->
<script>
// Checks if the browser is comptabile with HTML5 File API
if (window.File && window.FileReader && window.FileList && window.Blob) {
	// Browser has the FileReader API
} else {
	alert("The FILE APIs may not be fully supported in this browser.")
}

function handleFileSelect(evt) {
	var files = evt.target.files;
	var output = [];
	for (var i = 0, f; f = files[i]; i++) {
		output.push('<li><strong>', escape(f.name), '</strong></li>');
	}
	document.getElementById('list').innerHTML = '<ul>' + output.join('') + '</ul>';
}

document.getElementById('file[]').addEventListener('change', handleFileSelect, false);
</script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.14.0/jquery.validate.js"></script>
<script type="text/javascript" src="http://cdn.jsdelivr.net/jquery.validation/1.14.0/additional-methods.js"></script>

<script type="text/javascript" src="{% static 'js/vendor/jquery.ui.widget.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.iframe-transport.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.fileupload.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.fileupload-process.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.fileupload-validate.js' %}"></script>

<script>

	{% if error_msg %}
	alert("{{ error_msg }}");
	{% endif %}

	var update_list = function() {
		$.getJSON("{% url 'update-worklist' %}", function(data) {
			$("#id_file_upload_selection").empty();
			$.each(data, function() {
				$("#id_file_upload_selection").append(
					$("<option></option>").text(this.filename).val(this.id)
					);
			});
		});
	}

	var update_limits_list = function() {
		$.getJSON("{% url 'update-limitslist' %}", function(data) {
			$("#id_file_limits_upload_selection").empty();
			$.each(data, function() {
				$("#id_file_limits_upload_selection").append(
					$("<option></option>").text(this.filename).val(this.id)
					);
			});
		});
	}

</script>

<script>

	function csrfSafeMethod(method) {
	// These HTTP methods do not require CSRF protection
	return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

$(function () {
	'use strict';
	// Change this to the location of server-side upload handler;
	var url = 'upload/';
	var csrftoken = $.cookie('csrftoken');
	$('#fileupload').fileupload({
		url: url,
		crossDomain: false,
		beforeSend: function(xhr, settings) {
			if (!csrfSafeMethod(settings.type)) {
				xhr.setRequestHeader("X-CSRFToken", csrftoken);
			}
		},
		dataType: 'json',
		processQueue: [
		{
			action: 'validate',
			always: true,
			acceptFileTypes: /(\.|\/)(txt|csv)$/i
		}
		],
		processfail: function(e, data) {
			$('#files').empty();
			$('<p/>').text("File extension invalid, please upload a .csv file").appendTo('#files');
		},
		done: function(e, data) {
			$.each(data.files, function(index, file) {
				$('#files').empty();
				$('<p/>').text("File upload complete.").appendTo('#files');
				update_list();
			});
		},
		progressall: function(e, data) {
			var progress = parseInt(data.loaded / data.total * 100, 10);
			$('#progress .progress-bar').css(
				'width',
				progress + '%'
				);
		},
	}).prop('disabled', !$.support.fileInput)
	.parent().addClass($.support.fileInput ? undefined : 'disabled');
})
</script>

<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/pqanalysis.js' %}"></script>


<script src="//static.getclicky.com/js" type="text/javascript"></script>
<script type="text/javascript">try{ clicky.init(100988674); }catch(e){}</script>
<noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/100988674ns.gif" /></p></noscript>
{% endblock %}

bioinfoweb/pqanalysis/templates/pqanalysis/pqerror.html

{% load staticfiles %}

<html>
<head>
       <!-- The above 3 meta tags must come first in the head -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/non-responsive.css' %}">
        <link rel="stylesheet" href="{% static 'css/pqanalysis.css' %}">

        <link href='https://fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
        <link href='https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css' rel='stylesheet' type='text/css'>
</head>

<body>
	<h1>There was an error processing your request.</h1>
	<div class="row">
		<div class="col-xs-12">
			<h4>Error log</h4>
				{{ error_out|safe }}
		</div>
	</div>

	<br>

	<div class="row">
		<div class="col-xs-12">
			<h4>Common Cause For Errors:</h4>
			<ul>
				<li>Loaded incorrect file. Is it a @DI PCR file, @Pt2 LIS file or @VLI TMA file?</li>
				<li>Loaded only a single pair when program expected 2 (i.e. TMA analysis requires @Pt2 and @VLI).</li>
				<li>Loaded corrupt PCR file, is it blank or different from the standard PCR files?</li>
				<li>Loaded incorrect PCR data type, is it the incorrect assay type?</li>
			</ul>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">
			<p>If this error continues to persist, please inform David at david.bour@hologic.com.
			Please copy and paste the error log in the e-mail.</p>
		</div>
	</div>

</body>
</html>

bioinfoweb/pqanalysis/templates/pqanalysis/pqresults.html
<!DOCTYPE html>
{% load staticfiles %}


<html>
<head>
       <!-- The above 3 meta tags must come first in the head -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/non-responsive.css' %}">
        <link rel="stylesheet" href="{% static 'css/pqanalysis.css' %}">
        <link href='https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
</head>

<body>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="nav-bar-header">
			<a class="navbar-brand" href="#">PQ Analysis</a>
		</div>
	</div>

	<div class="collapse navbar-collapse">
		<ul class="nav navbar-nav">
			<li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home"></span>  Bioinformatics Home</a></li>
			<li><a href="{% url 'add_attachment' %}"><span class="glyphicon glyphicon-tasks"></span> PQ Home</a></li>
			<li><a href="{% url 'view_results' %}"><span class="glyphicon glyphicon-hdd"></span> PQ Results</a></li>
		</ul>
	</div>
</nav>


<div class="row">
	<div class="col-xs-1">
	</div>
	<div class="col-xs-9">
		<table class="table table-bordered" id="pqresultstable">
			<thead>
				<tr>
					<th>Index</th>
					<th>Submitter</th>
					<th>File Name</th>
					<th>Date Submitted</th>
					<th>Results</th>
				</tr>
			</thead>
			<tbody>
				{% for key, values in file_dict.items %}
				<tr>
					<td>
					{{ values.attachment.id }}
					</td>
					<td>
					{{ values.attachment.submitter }}
					</td>
					<td>
					{{ key }}
					</td>
					<td>
					{{ values.attachment.date_submitted }}
					</td>
					<td>
					<a href="{{ MEDIA_URL }}{{ values.html_dir }}">{{ key }}</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="col-xs-2">
	</div>
</div>

</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="{% static 'js/pqresults.js' %}"></script>


</html>